# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ChatApplication
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'IQKeyboardManagerSwift'
  pod 'iRecordView'
  pod 'GoogleSignIn', '< 5.0.0'
  pod 'Firebase/Storage'
end
